name: Docker Image CI

on:
  #   workflow_dispatch:
  #     inputs:
  #       tag:
  #         description: 'Test tag'
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 16
    
    - name: Install dependencies
      run: npm install
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: zhangxin8344
        password: ${{ secrets.DOCKER_LOGIN_TOKEN }}

    - name: Build the Docker image
      run: bash ./build_push.sh
      
    - name: Trigger Webhook
      uses: joelwmale/webhook-action@2.1.0
      with:
        url: ${{ secrets.PORTAINER_CONTAINER_WEBHOOK }}

